export default function robots() {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/assets/',
          '/static/',
          '/*.css$',
          '/*.js$',
          '/*.png$',
          '/*.jpg$',
          '/*.jpeg$',
          '/*.svg$',
          '/*.webp$',
          '/*.woff$',
          '/*.woff2$',
        ],
        disallow: [
          '/work/',
          '/work/suprabha',
          '/work/coretech',
          '/work/puttur',
          '/insights/drafts/',
          '/admin/',
          '/private/',
          '/api/',
          '/tmp/',
          '/backup/',
          '/test/',
          '/staging/',
          '/dev/',
          '/support/',
          '/wp-admin/',
          '/wp-includes/',
          '/wp-content/plugins/',
          '/wp-content/cache/',
          '/xmlrpc.php',
          '/wp-login.php',
          '/wp-config.php',
          '/readme.html',
          '/license.txt',
          '/*.json$',
          '/*.xml$',
          '/*?print=',
          '/*?share=',
          '/*?utm_',
          '/search?',
          '/*?s=',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: '/',
        disallow: [
          '/work/',
          '/insights/drafts/',
          '/admin/',
          '/private/',
          '/api/',
          '/support/',
        ],
      },
      {
        userAgent: 'Googlebot-Image',
        allow: '/',
        disallow: ['/private/', '/admin/'],
      },
      {
        userAgent: 'Googlebot-News',
        disallow: '/',
      },
      {
        userAgent: 'Bingbot',
        allow: '/',
        crawlDelay: 2,
        disallow: [
          '/work/',
          '/insights/drafts/',
          '/admin/',
          '/private/',
          '/api/',
          '/support/',
        ],
      },
      { userAgent: 'GPTBot', disallow: '/' },
      { userAgent: 'ChatGPT-User', allow: '/' },
      { userAgent: 'ClaudeBot', allow: '/' },
      { userAgent: 'anthropic-ai', disallow: '/' },
      { userAgent: 'Google-Extended', disallow: '/' },
      { userAgent: 'CCBot', disallow: '/' },
      { userAgent: 'PerplexityBot', allow: '/' },
      { userAgent: 'Applebot-Extended', disallow: '/' },
      { userAgent: 'Applebot', allow: '/' },
      { userAgent: 'FacebookBot', disallow: '/' },
      { userAgent: 'Meta-ExternalAgent', disallow: '/' },
      { userAgent: 'Bytespider', disallow: '/' },
      { userAgent: 'cohere-ai', disallow: '/' },
      { userAgent: 'Diffbot', disallow: '/' },
      { userAgent: 'omgili', disallow: '/' },
      { userAgent: 'AhrefsBot', allow: '/', crawlDelay: 10 },
      { userAgent: 'SemrushBot', allow: '/', crawlDelay: 10 },
      { userAgent: 'MJ12bot', disallow: '/', crawlDelay: 10 },
      { userAgent: 'DotBot', disallow: '/', crawlDelay: 10 },
      { userAgent: 'rogerbot', allow: '/', crawlDelay: 10 },
      { userAgent: 'Twitterbot', allow: '/' },
      { userAgent: 'facebookexternalhit', allow: '/' },
      { userAgent: 'LinkedInBot', allow: '/' },
      { userAgent: 'WhatsApp', allow: '/' },
      { userAgent: 'TelegramBot', allow: '/' },
      { userAgent: 'Slackbot', allow: '/' },
      { userAgent: 'Discordbot', allow: '/' },
      { userAgent: 'SiteSnagger', disallow: '/' },
      { userAgent: 'WebStripper', disallow: '/' },
      { userAgent: 'WebCopier', disallow: '/' },
      { userAgent: 'Fetch', disallow: '/' },
      { userAgent: 'Offline Explorer', disallow: '/' },
      { userAgent: 'HTTrack', disallow: '/' },
      { userAgent: 'Microsoft.URL.Control', disallow: '/' },
      { userAgent: 'psbot', disallow: '/' },
      { userAgent: 'NPBot', disallow: '/' },
      { userAgent: 'WWW-Collector-E', disallow: '/' },
      { userAgent: 'SiteAuditBot', disallow: '/' },
    ],
    sitemap: [
      'https://anideatech.in/sitemap.xml',
      'https://anideatech.in/sitemap-services.xml',
      'https://anideatech.in/sitemap-insights.xml',
    ],
    host: 'anideatech.in',
  };
}